### ISSUE TITLE
Regarding Issue Campaigns and queues Upload Audio File Issue #575

### ISSUE THREAD

**Issue by Khaled-IamZ** [magnussolution/magnusbilling#576]
@magnussolution import Audio File Not Fixed 
i have been installed MagnusBilling V 7.8.0.7 after your reply. and the above issue not resolved please find the below attached file including wait message  this message take more than an hour and didn't save the campaigns
FYI wav file size is 318KB and uploaded at ivr and magnuscallcenter4 without any issues
![Capture](https://user-images.githubusercontent.com/74547726/163468876-49d90043-1215-4c95-a7f4-5825cce6b7b2.JPG)

_Originally posted by @Khaled-IamZ in https://github.com/magnussolution/magnusbilling7/issues/575#issuecomment-1099589522_

**Comment by magnussolution** [comment]
fixed, please update

**Comment by Khaled-IamZ** [comment]
Dear @magnussolution 
i have been setup a fresh installation today on centos 7 and Debian 10 at different servers using the below
cd /usr/src/
yum -y install wget
wget https://raw.githubusercontent.com/magnussolution/magnusbilling7/source/script/install.sh
chmod +x install.sh
./install.sh
and get more issues.
1- import Audio File not resolved at campaigns section
2- the quick campaigns upload the file and didn't play to callee and the call goes failed
3- when make a call using sip account from softphone i got the number is declined 
so i Rollback to my backup installed on 18 March 2022 this is the same version but Stable release for me
please try to setup a fresh installation and check it
maybe the new update after 18 March has a problem
